#
#server:
#  port: 9001
#
#spring:
#  application:
#    name: xd-user-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: xxx
#
#  # rabbit mq config
#  rabbitmq:
#    host: xxx
#    port: xxx
#    virtual-host: /
#    password: password
#    username: admin
#    # manually confirm msg
#    listener:
#      simple:
#        acknowledge-mode: manual
#
#  # database config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxx/xd_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=US/Pacific
#    username: root
#    password: xxx
#  # redis config
#  redis:
#    host: xxx
#    port:xxx
#    password: xxx
#  # mail config
#  mail:
#    host: smtp.163.com # sending server
#    username: xxx
#    password: xxx # confirmation code
#    from: xxx # sending mail, same use username
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#
#
## config mybatis plus print sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
## config log level,ERROR/WARN/INFO/DEBUG,default is show when higher than INFO level
#logging:
#  level:
#    root: INFO
#
## Alibaba Cloud OSS config
#aliyun:
#  oss:
#    endpoint: xxx
#    access-key-id: xxx
#    access-key-secret: xxx
#    bucket-name: xxx
#
## seata config
##seata:
##  tx-service-group: ${spring.application.name}-group
##  service:
##    grouplist:
##      xdbob: 127.0.0.1:8091
##    vgroup-mapping:
##      xd-user-service-group: xdbob