#
#server:
#  port: xxx
#
#spring:
#  application:
#    name: xd-product-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: xx
#
#  # rabbit mq config
#  rabbitmq:
#    host: xxx
#    port: 5672
#    virtual-host: /
#    password: password
#    username: admin
#    # manually confirm msg
#    listener:
#      simple:
#        acknowledge-mode: manual
#
#  # database config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://120.24.94.xxx:xx/xd_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=US/Pacific
#    username: root
#    password: xxx
#  # redis config
#  redis:
#    host: xxx
#    port: xx
#    password: xxx
#
## config mybatis plus print sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
## config log level,ERROR/WARN/INFO/DEBUG,default is show when higher than INFO level
#logging:
#  level:
#    root: INFO
#
#
## custom mq config，send lock stock msg->delay exchange->lock.queue->dead letter exchange->release.queue
#mqconfig:
#  #delay queue, cannot be listened and consume
#  stock_release_delay_queue: stock.release.delay.queue
#
#  #redirect queue after msg expire
#  stock_release_queue: stock.release.queue
#
#  #exchange
#  stock_event_exchange: stock.event.exchange
#
#  #routing key for enter delay queue
#  stock_release_delay_routing_key: stock.release.delay.routing.key
#
#  #msg expire，routing key for enter release queue
#  stock_release_routing_key: stock.release.routing.key
#
#  #msg expire time,ms, 15ms in test
#  ttl: 15000