#
#
#server:
#  port: 8889
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 120.24.94.xxx:8848
#      config:
#        enabled: false
#
#    gateway:
#      routes: # array format
#        - id: product-service # product service, unique routing
#          uri: lb://xd-product-service  # redirect from nacos
#          order: 1 # priority，the less the number, the more priority
#          predicates: # assert config redirect which route can redirect，front end add:XXX-server，gateway redirect to needed service
#            - Path=/product-server/**
#          filters: # filter，request modified by filter in progress
#            - StripPrefix=1 # delete first level of prefix and redirect
#
#        - id: user-service # user service, unique routing
#          uri: lb://xd-user-service  # redirect from nacos
#          order: 2 # priority，the less the number, the more priority
#          predicates: # assert config redirect which route can redirect，front end add:XXX-server，gateway redirect to needed service
#            - Path=/user-server/**
#          filters: # filter，request modified by filter in progress
#            - StripPrefix=1 # delete first level of prefix and redirect
#
#        - id: coupon-service # coupon service, unique routing
#          uri: lb://xd-coupon-service  # redirect from nacos
#          order: 3 # priority，the less the number, the more priority
#          predicates: # assert config redirect which route can redirect，front end add:XXX-server，gateway redirect to needed service
#            - Path=/coupon-server/**
#          filters: # filter，request modified by filter in progress
#            - StripPrefix=1 # delete first level of prefix and redirect
#
#        - id: order-service # order service, unique routing
#          uri: lb://xd-order-service  # redirect from nacos
#          order: 3 # priority，the less the number, the more priority
#          predicates: # assert config redirect which route can redirect，front end add:XXX-server，gateway redirect to needed service
#            - Path=/order-server/**
#          filters: # filter，request modified by filter in progress
#            - StripPrefix=1 # delete first level of prefix and redirect
#
#
#
#      # allow gateway pull nacos service
#      discovery:
#        locator:
#          enabled: true
#
## config log level,ERROR/WARN/INFO/DEBUG,default is show when higher than INFO level
#logging:
#  level:
#    root: INFO
#    com.alibaba.nacos.client.config.impl: WARN
#
#
